apiVersion: v1
kind: Secret
metadata:
  name: dai-xld-rabbitmq-secret
  labels:
    rabbitmq.com/topology-operator: "true"
type: Opaque
stringData:
  username: guest
  password: guest
  default_user.conf: |
    default_user = guest
    default_pass = guest
  uri: http://dai-xld-rabbitmq:15672
  rabbitmq-erlang-cookie: DEPLOYRABBITMQCLUSTER